config/routes.rb
Rails.application.routes.draw do
  resources :next_appointments
  resources :appointments
  resources :animals
  resources :doctors

end

app/models/next_appointment.rb
class NextAppointment < ActiveRecord::Base
  belongs_to :appointment
end

app/controllers/next_appointments_controller.rb
class NextAppointmentsController < ApplicationController
  before_action :set_next_appointment, only: [:show, :edit, :update, :destroy]

  # GET /next_appointments
  # GET /next_appointments.json
  def index
    @next_appointments = NextAppointment.all
  end

  # GET /next_appointments/1
  # GET /next_appointments/1.json
  def show
  end

  # GET /next_appointments/new
  def new
    @next_appointment = NextAppointment.new
  end

  # GET /next_appointments/1/edit
  def edit
  end

  # POST /next_appointments
  # POST /next_appointments.json
  def create
    @next_appointment = NextAppointment.new(next_appointment_params)

    respond_to do |format|
      if @next_appointment.save
        format.html { redirect_to @next_appointment, notice: 'Next appointment was successfully created.' }
        format.json { render :show, status: :created, location: @next_appointment }
      else
        format.html { render :new }
        format.json { render json: @next_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /next_appointments/1
  # PATCH/PUT /next_appointments/1.json
  def update
    respond_to do |format|
      if @next_appointment.update(next_appointment_params)
        format.html { redirect_to @next_appointment, notice: 'Next appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @next_appointment }
      else
        format.html { render :edit }
        format.json { render json: @next_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /next_appointments/1
  # DELETE /next_appointments/1.json
  def destroy
    @next_appointment.destroy
    respond_to do |format|
      format.html { redirect_to next_appointments_url, notice: 'Next appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_next_appointment
      @next_appointment = NextAppointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def next_appointment_params
      params.require(:next_appointment).permit(:next_date, :appointment_id)
    end
end

app/helpers/next_appointments_helper.rb
module NextAppointmentsHelper
end

app/views/next_appointments/_form.html.erb
<%= form_for(@next_appointment) do |f| %>
  <% if @next_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@next_appointment.errors.count, "error") %> prohibited this next_appointment from being saved:</h2>

      <ul>
      <% @next_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :next_date %><br>
    <%= f.text_field :next_date %>
  </div>
  <div class="field">
    <%= f.label :appointment_id %><br>
    <%= f.text_field :appointment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/next_appointments/edit.html.erb
<h1>Editing Next Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @next_appointment %> |
<%= link_to 'Back', next_appointments_path %>

app/views/next_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Next Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Next date</th>
      <th>Appointment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @next_appointments.each do |next_appointment| %>
      <tr>
        <td><%= next_appointment.next_date %></td>
        <td><%= next_appointment.appointment %></td>
        <td><%= link_to 'Show', next_appointment %></td>
        <td><%= link_to 'Edit', edit_next_appointment_path(next_appointment) %></td>
        <td><%= link_to 'Destroy', next_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Next appointment', new_next_appointment_path %>

app/views/next_appointments/new.html.erb
<h1>New Next Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', next_appointments_path %>

app/views/next_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Next date:</strong>
  <%= @next_appointment.next_date %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @next_appointment.appointment %>
</p>

<%= link_to 'Edit', edit_next_appointment_path(@next_appointment) %> |
<%= link_to 'Back', next_appointments_path %>